export default `<span></span><span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>
<span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> 
<span></span>`;